"""The shipped provider preset catalogue, read from disk and never fetched.

Design: ``docs/plans/2026-09-13-ai-provider-model-routing-design.md`` §9.1.

``ai_provider_presets.json`` sits next to this module and is regenerated by
``scripts/build_ai_provider_presets.py`` from models.dev. It is committed on
purpose: the page that offers "add a provider" must work on a machine with no
route to models.dev, and a change to what this project suggests should be a
reviewed diff rather than something that shifts under a running deployment.

A preset is a starting point, not a claim about an account. The model ids come
from models.dev on the day the file was generated; what a key can actually
call is answered by "拉取模型列表" (§9.2), and the page says so.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)

PRESET_FILE = Path(__file__).with_name("ai_provider_presets.json")

#: What a caller gets when the file is missing or unreadable: the page still
#: renders, with the one preset that needs no data at all.
_FALLBACK: dict[str, Any] = {
    "generated_at": "",
    "source": "",
    "group_order": ["custom"],
    "group_labels": {"custom": "自定义"},
    "providers": [
        {
            "id": "custom",
            "group": "custom",
            "group_label": "自定义",
            "label": "自定义（OpenAI 兼容）",
            "english_label": "",
            "base_url": "",
            "doc_url": "",
            "requires_api_key": True,
            "note": "任何 OpenAI 兼容端点",
            "models": [],
        }
    ],
}


@lru_cache(maxsize=1)
def load_provider_presets(path: str | Path | None = None) -> dict[str, Any]:
    """The catalogue, grouped and ordered. Cached: the file ships with the code.

    Never raises. A broken catalogue must not be able to take the provider
    page down -- the page's job is editing what is already configured, and the
    presets only make adding a new one quicker.
    """

    target = Path(path) if path is not None else PRESET_FILE
    try:
        payload = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        logger.warning(
            "ai provider presets unreadable at %s; offering 自定义 only",
            target,
            exc_info=True,
        )
        return dict(_FALLBACK)
    if not isinstance(payload, dict) or not isinstance(payload.get("providers"), list):
        logger.warning("ai provider presets at %s are not a catalogue", target)
        return dict(_FALLBACK)
    return payload


def preset_models_by_id(
    presets: dict[str, Any] | None = None,
) -> dict[str, dict[str, Any]]:
    """Every preset model, keyed by model id, for capability lookups.

    A model fetched live from a provider only says its id, so this is how the
    page knows that ``qwen3.8-flash`` takes images while ``deepseek-chat``
    does not, without asking the person.
    """

    catalogue = presets if presets is not None else load_provider_presets()
    models: dict[str, dict[str, Any]] = {}
    for provider in catalogue.get("providers", []):
        for model in provider.get("models", []) or []:
            model_id = str(model.get("id") or "")
            if model_id and model_id not in models:
                models[model_id] = model
    return models


def find_preset(
    preset_id: str,
    presets: dict[str, Any] | None = None,
) -> dict[str, Any] | None:
    catalogue = presets if presets is not None else load_provider_presets()
    for provider in catalogue.get("providers", []):
        if str(provider.get("id")) == str(preset_id):
            return provider
    return None
